### ISSUE TITLE
detection of libedit should not disable completion

### ISSUE THREAD

**Issue by steckerhalter** [joddie/boris#1] opened 2013-08-17 17:49 UTC
Hi... thanks for picking it up again.

So I was testing the latest changes and using libedit the completion works too, so I think the check is not necessary:

``` php
    if ($rl_info['library_version'] == 'EditLine wrapper') {
      print "Boris tab completion disabled (requires PHP compiled with GNU readline, not libedit).\n";
    } else {
      readline_completion_function(array($this, 'completion_function'));
    }
```

I think the only function libedit does not support is php.net/manual/en/function.readline-list-history.php

I still get segfaults and also plenty of notices like that:

```
PHP Notice:  Trying to get property of non-object in lib/Boris/ReadlineClient.php on line 132'
```

**Comment by joddie** [comment] 2013-08-17 20:17
AFAICT, PHP's interface to libedit doesn't have a way to get the complete line entered so far, which is a show stopper for context-aware completion. What's the output if you put `var_export($rl_info)` after line 125 (`$rl_info = readline_info();`) in ReadlineClient.php? With GNU readline, there are values for the keys `'line_buffer'` and `'point'`. Without those values, we might still be able to complete function and class names, but not object members or anything else that requires examining the rest of the line. I guess that could still be useful.

The notices are probably related to a not-very-smart socket messaging protocol, which needs reworking anyway. I will try to run with more warnings enabled and debug them when I have time.

Do you still get segfaults if you run under a PHP interpreter linked with GNU readline? (With OS X + Macports this was easy to get, but I believe licensing issues make it harder to obtain on some Linux distributions).

**Comment by steckerhalter** [comment] 2013-08-17 20:23
I checked the output of readline_info() already... line_buffer and point were both present.

**Comment by joddie** [comment] 2013-08-17 20:25
Hmm, that's interesting. The segfaults are worrying, though. Any specific steps to reproduce?

**Comment by steckerhalter** [comment] 2013-08-17 20:33
Ok. Assumed I had GNU readline in the other VM but it seems to be libedit too... so let me check with that first.

**Comment by steckerhalter** [comment] 2013-08-17 21:52
Seems to be pretty hard to get GNU readline with PHP on Linux, they all use libedit because of licensing issues. I'm not sure if demanding GNU readline is even the way to go like that.

**Comment by joddie** [comment] 2013-08-17 23:14
Yeah. It should be possible to do a limited amount of completion with libedit by using just the part of the line that gets passed as a parameter to the callback. You could get at least function/class/constant names, which would be better than nothing, I agree. 

Even with GNU readline the completion is less than ideal due to the limited interface PHP's extension provides: you have to press TAB twice, it inserts extra spaces after things, etc. I've been more interested in emacs integration for that reason.

**Comment by joddie** [comment] 2013-08-17 23:38
I added support for basic symbol completion for libedit in 89f976a.

**Comment by steckerhalter** [comment] 2013-08-17 23:54
Hmm, is the reason for the different callback the missing 'line_buffer' and 'point' on your side?

Because my libedit has this included:

``` php
$ bin/joddie/bin/boris
[1] boris> fope
array(6) {
  ["line_buffer"]=>
  string(4) "fope"
  ["point"]=>
  int(4)
  ["end"]=>
  int(4)
  ["library_version"]=>
  string(16) "EditLine wrapper"
  ["readline_name"]=>
  string(0) ""
  ["attempted_completion_over"]=>
  int(0)
}

n(
```

**Comment by joddie** [comment] 2013-08-18 00:03
Huh, I guess so.  I just tried it with the normal callback on a linux host and indeed it works.  It must be an OS X/Macports specific bug.  What a pain.

Do you still see segfaults / lots of warnings?

**Comment by steckerhalter** [comment] 2013-08-18 00:09
yes, after pressing tab a few times:

```
$ bin/boris 
[1] boris> 
[1]     *> 
[1]     *> fopen(
Segmentation fault
```

the completion of fopen works. hmm, just checked. it doesn't segfault using your new libedit code...

**Comment by joddie** [comment] 2013-08-18 00:09
That may be an easy fix.  libedit doesn't like it when you return an empty array.

**Comment by joddie** [comment] 2013-08-18 00:13
Try from the latest commit?

**Comment by steckerhalter** [comment] 2013-08-18 00:20
indeed, no segfaulting anymore :+1:

**Comment by joddie** [comment] 2013-08-19 21:40
BTW, since you're an Emacs user too, please test out elisp/boris-completion.el and see if it works for you. It provides completion, live doc/source lookup and Eldoc argument lists in PHP source buffers.  If my changes can eventually be merged into boris in some form it would be good to combine this, php-boris and your php-boris-minor-mode into one package.

**Comment by steckerhalter** [comment] 2013-08-20 10:27
> If my changes can eventually be merged into boris in some form it would be good to combine this, php-boris and your php-boris-minor-mode into one package.

Yes. See my comment on the issue above.

**Closed as completed** 2013-08-22 10:50 UTC
